inception

diff --git a/Circolo5/inception/Makefile b/Circolo5/inception/Makefile
--- a/Circolo5/inception/Makefile
+++ b/Circolo5/inception/Makefile
@@ -18,21 +18,23 @@ help:
 	@echo "  restart  - Restart Docker containers"
 	@echo ""
 	@echo "Before launching, change the value of USER_LOGIN in srcs/.env"
+	@echo "Also, add the line 127.0.0.1 fcardina.42.it to host machine /etc/hosts"
 	@echo ""
 
 # Setup target to create necessary directories and set permissions
-setup:
-	@echo "Setting up directories..."
-	@sudo mkdir -p /home/$(USER_LOGIN)/data/wordpress || true
-	@sudo mkdir -p /home/$(USER_LOGIN)/data/mariadb || true
-	@sudo chown -R $(USER_LOGIN):$(USER_LOGIN) /home/$(USER_LOGIN)/data/mariadb || true
-	@sudo chown -R $(USER_LOGIN):$(USER_LOGIN) /home/$(USER_LOGIN)/data/wordpress || true
-	@sudo chmod -R 755 /home/$(USER_LOGIN)/data/mariadb || true
-	@sudo chmod -R 755 /home/$(USER_LOGIN)/data/wordpress || true
-	@echo "Setup complete."
+#setup:
+#	@sudo hostsed add 127.0.0.1 fcardina.42.fr && echo "fcardina.42.fr added to /etc/hosts"
+#	@echo "Setting up directories..."
+#	@sudo mkdir -p /home/$(USER_LOGIN)/data/wordpress || true
+#	@sudo mkdir -p /home/$(USER_LOGIN)/data/mariadb || true
+#	@sudo chown -R $(USER_LOGIN):$(USER_LOGIN) /home/$(USER_LOGIN)/data/mariadb || true
+#	@sudo chown -R $(USER_LOGIN):$(USER_LOGIN) /home/$(USER_LOGIN)/data/wordpress || true
+#	@sudo chmod -R 755 /home/$(USER_LOGIN)/data/mariadb || true
+#	@sudo chmod -R 755 /home/$(USER_LOGIN)/data/wordpress || true
+#	@echo "Setup complete."
 
 # Default target: Build and start the containers
-up: setup
+up: #setup
 	@echo "Starting Docker containers..."
 	@$(DOCKER_COMPOSE) up -d --build
 	@echo "Containers are up and running."
@@ -40,7 +42,7 @@ up: setup
 # Remove the containers and network
 down:
 	@echo "Stopping Docker containers, removing volumes..."
-	@$(DOCKER_COMPOSE) down -v
+	@$(DOCKER_COMPOSE) down --rmi all -v
 	@echo "Containers stopped."
 
 # Remove the containers, network, and volumes
@@ -50,8 +52,21 @@ clean: down
 	@sudo rm -rf /home/$(USER_LOGIN)/data/mariadb
 	@echo "Cleanup complete."
 
+# More thorough cleanup 
+fclean: clean
+#	@sudo hostsed rm 127.0.0.1 fcardina.42.fr && echo "fcardina.42.fr removed from /etc/hosts"
+	@if [ -d "/home/$(USER_LOGIN)/data/wordpress" ]; then \
+	sudo rm -rf /home/$(USER_LOGIN)/data/wordpress/* && \
+	echo "Removed all local contents from /home/USER_LOGIN/data/wordpress/"; \
+	fi;
+
+	@if [ -d "/home/fcardina/data/mariadb" ]; then \
+	sudo rm -rf /home/fcardina/data/mariadb/* && \
+	echo "Removed all local contents from /home/USER_LOGIN/data/mariadb/"; \
+	fi;
+
 # Restart containers
-restart: clean up
+restart: fclean up
 
 # View the logs of all services
 logs:
